. (Join-Path $PSScriptRoot 'Octosprache.Init.ps1')
. (Join-Path $PSScriptRoot 'Octosprache.Class.ps1')
. (Join-Path $PSScriptRoot 'OctopusEncoder.Class.ps1')
. (Join-Path $PSScriptRoot 'TeamCityEncoder.Class.ps1')
. (Join-Path $PSScriptRoot 'AutoMetrics.Class.ps1')